version: '3'

tasks:
  up:
    cmds:
      - sudo docker image rm eventtom-backend eventtom-prestart eventtom-frontend -f
      - sudo docker compose  --env-file .env up
  down: 
    cmds:
      - sudo docker compose  --env-file .env down
      - sudo docker image rm eventtom-prestart eventtom-backend